// <auto-generated />
using System;
using BandSpirit.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BandSpirit.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BandSpiritDbContext))]
    [Migration("20260921142318_DB12_FirmaSingletonCheck")]
    partial class DB12_FirmaSingletonCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BandSpirit.Api.Models.AppLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("Modul");

                    b.HasIndex("UserId");

                    b.ToTable("AppLogs", t =>
                        {
                            t.HasCheckConstraint("CK_AppLogs_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.BIGuideNews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Inhalt")
                        .HasColumnType("text");

                    b.Property<string>("Kategorie")
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Wichtig")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("BIGuideNews", t =>
                        {
                            t.HasCheckConstraint("CK_BIGuideNews_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.BIKompassVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aenderungen")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Inhalt")
                        .HasColumnType("text");

                    b.Property<bool>("IsAktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BIKompassVersionen", t =>
                        {
                            t.HasCheckConstraint("CK_BIKompassVersionen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.BenutzerRolle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IstSystemAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BenutzerRollen", t =>
                        {
                            t.HasCheckConstraint("CK_BenutzerRollen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.BiGuideKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Farbe")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BiGuideKategorien", t =>
                        {
                            t.HasCheckConstraint("CK_BiGuideKategorien_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Antwort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Frage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kategorie")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FAQs", t =>
                        {
                            t.HasCheckConstraint("CK_FAQs_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.Firma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firmenname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Hausnummer")
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("LogoUrl");

                    b.Property<bool>("LogoPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Ort")
                        .HasColumnType("text");

                    b.Property<string>("Plz")
                        .HasColumnType("text");

                    b.Property<string>("Strasse")
                        .HasColumnType("text")
                        .HasColumnName("Adresse");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Versionsnummer")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Firmas", t =>
                        {
                            t.HasCheckConstraint("CK_Firmas_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");

                            t.HasCheckConstraint("CK_Firmas_NurSingleton", "\"Id\" = 'singleton'");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KeyResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Einheit")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Faelligkeit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("IstWert")
                        .HasColumnType("double precision");

                    b.Property<Guid>("OkrId")
                        .HasColumnType("uuid");

                    b.Property<double>("StartWert")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ZielWert")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OkrId");

                    b.ToTable("KeyResults", t =>
                        {
                            t.HasCheckConstraint("CK_KeyResults_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KpiDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid?>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Datenquelle")
                        .HasColumnType("text");

                    b.Property<string>("Einheit")
                        .HasColumnType("text");

                    b.Property<string>("Kategorie")
                        .HasColumnType("text");

                    b.Property<double?>("KritischeSchwelle")
                        .HasColumnType("double precision");

                    b.Property<string>("Messintervall")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Richtung")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerantwortlicherUserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Warnschwelle")
                        .HasColumnType("double precision");

                    b.Property<double?>("Zielwert")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.ToTable("KpiDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_KpiDefinitions_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KpiMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("IstWert")
                        .HasColumnType("double precision");

                    b.Property<string>("Kommentar")
                        .HasColumnType("text");

                    b.Property<Guid>("KpiDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Massnahme")
                        .HasColumnType("text");

                    b.Property<DateTime>("Messdatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trend")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KpiDefinitionId");

                    b.HasIndex("Messdatum");

                    b.ToTable("KpiMeasurements", t =>
                        {
                            t.HasCheckConstraint("CK_KpiMeasurements_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.MailVerteiler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("S3CircleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("S3RollenDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("S3CircleId");

                    b.HasIndex("S3RollenDefinitionId");

                    b.HasIndex("Typ");

                    b.ToTable("MailVerteiler", t =>
                        {
                            t.HasCheckConstraint("CK_MailVerteiler_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.MailVerteilerBenutzer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailVerteilerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MailVerteilerId", "UserId")
                        .IsUnique();

                    b.ToTable("MailVerteilerBenutzer", t =>
                        {
                            t.HasCheckConstraint("CK_MailVerteilerBenutzer_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.OKR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid?>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Faelligkeit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fortschritt")
                        .HasColumnType("integer");

                    b.Property<string>("Kategorie")
                        .HasColumnType("text");

                    b.Property<string>("Prioritaet")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerantwortlicherUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ZyklusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("ZyklusId");

                    b.ToTable("OKRs", t =>
                        {
                            t.HasCheckConstraint("CK_OKRs_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.OkrZyklus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OkrZyklen", t =>
                        {
                            t.HasCheckConstraint("CK_OkrZyklen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", t =>
                        {
                            t.HasCheckConstraint("CK_PasswordResetTokens_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Role", "Permission")
                        .IsUnique();

                    b.ToTable("RolePermissions", t =>
                        {
                            t.HasCheckConstraint("CK_RolePermissions_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Circle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LifecyclePhase")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RootId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Verantwortlichkeit")
                        .HasColumnType("text");

                    b.Property<string>("Zweck")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LifecyclePhase");

                    b.HasIndex("ParentId");

                    b.HasIndex("RootId");

                    b.ToTable("S3Circles", t =>
                        {
                            t.HasCheckConstraint("CK_S3Circles_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3CircleLebenszyklus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LebenszyklusPhaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("S3CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LebenszyklusPhaseId");

                    b.HasIndex("S3CircleId");

                    b.HasIndex("StartDatum");

                    b.ToTable("S3CircleLebenszyklen", t =>
                        {
                            t.HasCheckConstraint("CK_S3CircleLebenszyklen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3CircleReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ergebnis")
                        .HasColumnType("text");

                    b.Property<string>("Massnahmen")
                        .HasColumnType("text");

                    b.Property<string>("Notizen")
                        .HasColumnType("text");

                    b.Property<string>("Protokoll")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReviewDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.ToTable("S3CircleReviews", t =>
                        {
                            t.HasCheckConstraint("CK_S3CircleReviews_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntscheidDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("S3Decisions", t =>
                        {
                            t.HasCheckConstraint("CK_S3Decisions_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entscheid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EntscheidDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Prioritaet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.ToTable("S3Drivers", t =>
                        {
                            t.HasCheckConstraint("CK_S3Drivers_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3LebenszyklusPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Aktiv");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("S3LebenszyklusPhasen", t =>
                        {
                            t.HasCheckConstraint("CK_S3LebenszyklusPhasen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("S3Meetings", t =>
                        {
                            t.HasCheckConstraint("CK_S3Meetings_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3MeetingAgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("S3MeetingAgendaItems", t =>
                        {
                            t.HasCheckConstraint("CK_S3MeetingAgendaItems_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Objection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomainReference")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Risk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.HasIndex("UserId");

                    b.ToTable("S3Objections", t =>
                        {
                            t.HasCheckConstraint("CK_S3Objections_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3PersonRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("S3PersonRoleAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_S3PersonRoleAssignments_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresParentApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("MeetingId");

                    b.ToTable("S3Proposals", t =>
                        {
                            t.HasCheckConstraint("CK_S3Proposals_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<Guid>("CircleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCoordinator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFacilitator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RollenDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CircleId");

                    b.HasIndex("RollenDefinitionId");

                    b.HasIndex("CircleId", "RollenDefinitionId")
                        .IsUnique();

                    b.ToTable("S3Roles", t =>
                        {
                            t.HasCheckConstraint("CK_S3Roles_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3RolleDokument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DateigroesseBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RollenDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePfad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RollenDefinitionId");

                    b.ToTable("S3RolleDokumente", t =>
                        {
                            t.HasCheckConstraint("CK_S3RolleDokumente_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3RolleKennzahl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Einheit")
                        .HasColumnType("text");

                    b.Property<Guid>("RollenDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Zielwert")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RollenDefinitionId");

                    b.ToTable("S3RolleKennzahlen", t =>
                        {
                            t.HasCheckConstraint("CK_S3RolleKennzahlen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3RollenDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domaene")
                        .HasColumnType("text");

                    b.Property<bool>("IsLeadLink")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Verantwortlichkeit")
                        .HasColumnType("text");

                    b.Property<string>("Zweck")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("S3RollenDefinitionen", t =>
                        {
                            t.HasCheckConstraint("CK_S3RollenDefinitionen_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.SpannungWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ZugewiesenAnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ZugewiesenAnId");

                    b.ToTable("SpannungWorkItems", t =>
                        {
                            t.HasCheckConstraint("CK_SpannungWorkItems_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.Stammdaten", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kategorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Wert")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kategorie", "Code")
                        .IsUnique();

                    b.ToTable("Stammdaten", t =>
                        {
                            t.HasCheckConstraint("CK_Stammdaten_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Antwort")
                        .HasColumnType("text");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ErstellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kategorie")
                        .HasColumnType("text");

                    b.Property<string>("Prioritaet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ErstellerId");

                    b.ToTable("SupportTickets", t =>
                        {
                            t.HasCheckConstraint("CK_SupportTickets_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbacusPersonalnummer")
                        .HasColumnType("text");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("ChangedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedById")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailCanonical")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PortraetPfad")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmailCanonical")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_GueltigAbVorGueltigBis", "\"DateFrom\" IS NULL OR \"DateTo\" IS NULL OR \"DateFrom\" <= \"DateTo\"");
                        });
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KeyResult", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.OKR", "Okr")
                        .WithMany("KeyResults")
                        .HasForeignKey("OkrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okr");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KpiDefinition", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId");

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KpiMeasurement", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.KpiDefinition", "KpiDefinition")
                        .WithMany("Measurements")
                        .HasForeignKey("KpiDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KpiDefinition");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.MailVerteiler", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", null)
                        .WithMany()
                        .HasForeignKey("S3CircleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BandSpirit.Api.Models.S3RollenDefinition", null)
                        .WithMany()
                        .HasForeignKey("S3RollenDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BandSpirit.Api.Models.MailVerteilerBenutzer", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.MailVerteiler", "MailVerteiler")
                        .WithMany("Mitglieder")
                        .HasForeignKey("MailVerteilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailVerteiler");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.OKR", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId");

                    b.HasOne("BandSpirit.Api.Models.OkrZyklus", "Zyklus")
                        .WithMany()
                        .HasForeignKey("ZyklusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Circle");

                    b.Navigation("Zyklus");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BandSpirit.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.RolePermission", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.BenutzerRolle", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Circle", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BandSpirit.Api.Models.S3Circle", null)
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3CircleLebenszyklus", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3LebenszyklusPhase", "LebenszyklusPhase")
                        .WithMany()
                        .HasForeignKey("LebenszyklusPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.S3Circle", "S3Circle")
                        .WithMany()
                        .HasForeignKey("S3CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LebenszyklusPhase");

                    b.Navigation("S3Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3CircleReview", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Decision", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Proposal", "Proposal")
                        .WithOne("Decision")
                        .HasForeignKey("BandSpirit.Api.Models.S3Decision", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Driver", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Meeting", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3MeetingAgendaItem", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Meeting", "Meeting")
                        .WithMany("AgendaItems")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Objection", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Proposal", "Proposal")
                        .WithMany("Objections")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3PersonRoleAssignment", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Role", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Proposal", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.S3Meeting", null)
                        .WithMany("Proposals")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Circle");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Role", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Circle", "Circle")
                        .WithMany()
                        .HasForeignKey("CircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.S3RollenDefinition", "RollenDefinition")
                        .WithMany()
                        .HasForeignKey("RollenDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circle");

                    b.Navigation("RollenDefinition");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3RolleDokument", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3RollenDefinition", "RollenDefinition")
                        .WithMany()
                        .HasForeignKey("RollenDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RollenDefinition");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3RolleKennzahl", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3RollenDefinition", "RollenDefinition")
                        .WithMany()
                        .HasForeignKey("RollenDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RollenDefinition");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.SpannungWorkItem", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.S3Driver", "Driver")
                        .WithMany("WorkItems")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BandSpirit.Api.Models.User", "ZugewiesenAn")
                        .WithMany()
                        .HasForeignKey("ZugewiesenAnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");

                    b.Navigation("ZugewiesenAn");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.SupportTicket", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.User", "Ersteller")
                        .WithMany()
                        .HasForeignKey("ErstellerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ersteller");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.User", b =>
                {
                    b.HasOne("BandSpirit.Api.Models.BenutzerRolle", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BandSpirit.Api.Models.KpiDefinition", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.MailVerteiler", b =>
                {
                    b.Navigation("Mitglieder");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.OKR", b =>
                {
                    b.Navigation("KeyResults");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Driver", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Meeting", b =>
                {
                    b.Navigation("AgendaItems");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Proposal", b =>
                {
                    b.Navigation("Decision");

                    b.Navigation("Objections");
                });

            modelBuilder.Entity("BandSpirit.Api.Models.S3Role", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
